CREATE TABLE USERS(USER_ID INT PRIMARY KEY, USERNAME VARCHAR(255), FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), EMAIL VARCHAR(255), PASSWORD VARCHAR(255), ENABLED BOOLEAN, CREATION_DATE DATE);
CREATE TABLE USER_ROLES(USER_ROLE_ID INT PRIMARY KEY, ROLE_NAME VARCHAR(255));
